void enter();
void separe(char *ip,int* bits_reseau);
void msr(int *bits_reseau,char *ip1,char *ip2,char *ip3,char *ip4);
int binaire(int *tab);
void decimal(int x,char* chaine);
void reseau_exec(int *bits_reseau,char *ip1,char *ip2,char *ip3,char *ip4,char *msr1,char *msr2,char *msr3,char *msr4,char *adr_reseau,char *adr_broadcast);
int* reseau(char *chaine1, char *chaine2);
void binaire_reverse(int *sous_reseau,int *chaine1) ;
void broadcast(int *bits_reseau,int *reseau1,int *reseau2,int *reseau3,int *reseau4,char *adr_reseau,char *adr_broadcast);
void boucle(int *bits_reseau,int *decoup);
int nbre_machine(int bits_host);
void display(char *adr_reseau, char *adr_broadcast,int *bits_host, int decoup);
int * get(int *adresse_reseau, int number_of_machine);
